version: '3.8'

services:
  reverse-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
      - client

  server:
    build:
      context: .
      dockerfile: Dockerfile_server
    volumes:
      - server-data:/data

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - client-data:/usr/share/nginx/html
    environment:
      - API_URL=http://192.168.86.166/api/

volumes:
  client-data:
  server-data:

networks:
  app-network:
    driver: bridge
